[ADD] web_backend_theme_af, web_a11y_filter_view: AFC-1445 Added mode…
vertelab/odoo-web pull request #5
Opened 2020-11-24 09:39 UTC by rupareliyahemangi145

…l name in Create and Edit button.

2020-11-25 07:39 UTC, arturchilangwa-vertel requested changes
@rupareliyahemangi145 
We try as much possible to not commit commented code. 
If there is any strong reason for it, please write it in a comment above the commented code.
Please make a new PR or commit a change to this PR that removes the commented code.

2020-11-25 07:43 UTC, rupareliyahemangi145 commented
Ok @arturchilangwa-vertel I will remove comment.

2020-11-25 09:48 UTC, rupareliyahemangi145 commented
@arturchilangwa-vertel Removed commented code.

2020-11-27 13:39 UTC, daerio approved these changes

2020-11-27 13:39 UTC, merged